### ISSUE TITLE
Infinite Shutdown!

### ISSUE THREAD

**Issue by TheDemystifier** [prsyahmi/GpuRamDrive#12]
If I press 'Shutdown' before un-mounting the drive, Windows keeps shutting down forever, I have to hold power button to shut it down! Which is unhealthy!

Could you add an "automatic un-mount" when the program receives a shutdown/close notice ?

Also, Can you automatically format the drive upon mounting ?

**Comment by prsyahmi** [comment]
I added auto unmount when received shutdown notification, please try with latest version and see if it fixed your issue.

**Comment by TheDemystifier** [comment]
Great! Works likes a charm now! Tried shutting down couple time and logging off! Works great! I had another issue which was solved in this update! Will keep using it everyday, if anything comes up! I'll notify you.

You can close this issue!
