### ISSUE TITLE
Problem with CUDA (maybe just me)

### ISSUE THREAD

**Issue by remilia15** [prsyahmi/GpuRamDrive#16]
I had this warning while I was trying to use CUDA version of GpuRamDrive
![image](https://user-images.githubusercontent.com/13411810/33921626-aea6f56c-dff7-11e7-9d5e-8c46eea7174c.png)

Normal version does the job just fine
![image](https://user-images.githubusercontent.com/13411810/33921670-e4159848-dff7-11e7-987a-8e10d11ea106.png)

May I ask what's the difference between CUDA and the normal one?

**Comment by prsyahmi** [comment]
The CUDA version is slightly faster but not much.

**Comment by remilia15** [comment]
Thanks. So I'll just use the normal version instead
