### ISSUE TITLE
Unable to Create Memory Buffer on Intel HD Graphics 4000

### ISSUE THREAD

**Issue by DaijobuDes** [prsyahmi/GpuRamDrive#21]
It seems that I cannot create a GPURamDrive on Intel HD Graphics 4000 but when on my NVIDIA GT 610M it only works.

![image](https://user-images.githubusercontent.com/38452446/51660714-9b02be00-1fe9-11e9-9b13-927ce92a30da.png)

**Comment by Pummelchen** [comment]
This is supposed to be used with GPUs which have their own RAM.

**Comment by xCuri0** [comment]
Try creating it with less RAM I was able to use the 512MB of dedicated iGPU VRAM with https://github.com/brzz/GpuRamDrive (fork of this with amd fixed) on my AMD APU. If I used too much RAM I would get this same error
