### ISSUE TITLE
how do i use/install?

### ISSUE THREAD

**Issue by Robertcop** [prsyahmi/GpuRamDrive#3]
i tried to follow what you said. it doesnt seem to work. i mean i can't find the output dll you're talking about. i put everything into the same Dir as you asked. what did i do wron? :(

**Comment by prsyahmi** [comment]
Hi, download from here: https://github.com/prsyahmi/GpuRamDrive/releases/tag/v0.1

Make sure you have ImDisk and vcredist 2015 installed.
