### ISSUE TITLE
The code execution cannot proceed because OpenCL.dll was not found!

### ISSUE THREAD

**Issue by TheDemystifier** [prsyahmi/GpuRamDrive#37]
![](https://i.imgur.com/2EjD9HU.png)

**Comment by ltomes** [comment]
I believe I was seeing this issue before installing required dependencies. Is ImDisk installed?

https://github.com/prsyahmi/GpuRamDrive#usage

**Comment by TheDemystifier** [comment]
Yes.
![](https://i.imgur.com/z1iqH9M.png)

![](https://i.imgur.com/DEKiSKv.png)

**Comment by TheDemystifier** [comment]
Solved! Had to reinstall nVidia Graphics Driver. Seems the 20H2 update messed up a lot of things, first fonts were missing and now the GPU driver is corrupt. \****Sigh\****
