### ISSUE TITLE
Error in windows 10

### ISSUE THREAD

**Issue by ronen1n** [prsyahmi/GpuRamDrive#8]
when i try to open the program this error pop
![default](https://cloud.githubusercontent.com/assets/20344644/24076126/1baa7598-0c32-11e7-9d5e-94c5870e6dba.PNG)

**Comment by zSoulweaver** [comment]
Install ImDisk

**Comment by prsyahmi** [comment]
ImDisk link: http://www.ltr-data.se/opencode.html/
